### ISSUE TITLE
This was such a great course btw! few issues

### ISSUE THREAD

**Issue by 1997showroom** [KeithGalli/GUI#2]
I am running on an issue with the 'import requests' line
and also something is going on with the 'lambda'

#####
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/singlefawn/PycharmProjects/test/exportToHTML/1997-02.py", line 55, in <lambda>
    button = tk.Button(frame, text="Get Weather", font=40, command=lambda: get_weather(entry.get()))
  File "/Users/singlefawn/PycharmProjects/test/exportToHTML/1997-02.py", line 31, in get_weather
    response = requests.get(url, params=params)
NameError: name 'requests' is not defined
####

What's really cool about your videos are you actually are a great teacher, the beat was great I was able to learn through two sitting sessions of your video for about 4 hours all together. I started learning python two months ago now and moving into actually building a desktop app that runs was a big leap. This one video has exposed me to API understanding all the relwidth stuff plenty of really cool stuff. Please keep up the good work!

**Comment by KeithGalli** [comment]
Will respond with some feedback when I get back to my computer tomorrow. Bump this thread if you don't hear me and thanks for the kind feedback!

**Comment by 1997showroom** [comment]
> Will respond with some feedback when I get back to my computer tomorrow. Bump this thread if you don't hear me and thanks for the kind feedback!

Amazing and also how do you give your tk program a title in the title bar at top instead of it saying "tk"

I'm just getting to the library to go try the next tutorial you have on your youtube!!

**Comment by hannansatopay** [comment]
@KeithGalli I was browsing on GitHub and happened to stumble upon this repository. I hope you don't mind me answering the query.

@1997showroom 
1. You have to first install the requests library to be able to use that particular command without getting any error. The easy way to do that is to run the following command in your command prompt - `pip install requests`
Also, do not forget to import the requests library as already shown in the code shared in this repository.
Just additional information: the requests library allows you to work with APIs such as the weather API in this particular case.

2. You can easily change the title of the window by using the following code - 
`root.title('Weather App')`
You should put this code just below the statement `root = tk.Tk()`

**Comment by 1997showroom** [comment]
is it possible to hire you as developer for this new project im working on?
What are your levels of expertise with programing, what kind of things do
you do ??
singlefawn.com

**Comment by hannansatopay** [comment]
@1997showroom 
Yes, I am available to work as a developer on a wide variety of projects. I can work on the following project category: Data Science, Machine Learning, Cloud, Computer Vision, Web Development, App Development, Internet of Things just to name a few.
I am fluent in Python (and all related libraries...even Flask), HTML/CSS/Javascript, PHP, Wordpress, R, C & C++.
You can connect with me on LinkedIn where we can discuss further: https://www.linkedin.com/in/hannansatopay/

**Comment by 1997showroom** [comment]
https://www.dropbox.com/s/uqj5t1qv9qcuws6/1997%20Showroom%20-%20Client%20Pitch%20Deck.pdf?dl=0
singlefawn.com

**Comment by hannansatopay** [comment]
@1997showroom I have gone through the Presentation file and it looks really neat! I am assuming you want a company website to be developed? I can definitely do that. Any way we can get in touch?

**Comment by 1997showroom** [comment]
Amazing we will need some web stuff to but right now I want to start with a
smaller a project a desktop simple app that helps us do our job better its
a simple image layout generator. It's something I'm building that will help
us internally, I will be able to design all UI and content assets I also am
very hands on with all the function that it does and will have everything
listed in detail. When this next week is a good time to have a intro call
and move forward?
singlefawn.com

**Comment by 1997showroom** [comment]
I can do whats app, I'm in the states
singlefawn.com

**Comment by 1997showroom** [comment]
I also added you on linkedin
Im Imani Waddy
singlefawn.com

**Comment by 1997showroom** [comment]
did you get my email?
singlefawn.com

**Comment by hannansatopay** [comment]
Yes, I have replied to you via email. We can carry forward our conversation over there!
